name: Run Scraper

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # ← Add this block so the job can see your secrets
    env:
      EMAIL_ADDRESS:  ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      TARGET_URL:     ${{ secrets.TARGET_URL }}
      SMTP_SERVER:    ${{ secrets.SMTP_SERVER }}
      SMTP_PORT:      ${{ secrets.SMTP_PORT }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
