name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
